apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: petclinic-ptc-deploy
labels:
  app.kubernetes.io/name: petclinic-ptc
  app.kubernetes.io/instance: petclinic-ptc-main
  app.kubernetes.io/part-of: petclinic-ptc
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: petclinic-ptc
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/instance: petclinic-ptc-main
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: petclinic-ptc-main
          annotations:
            containerid: ${CONTAINER_ID}
        spec:
          containers:
            - name: petclinic-ptc
              image: prj-elcavn-training-docker.artifactory.svc.elca.ch/devops-final-exercise-ptc/petclinic-ptc:latest
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: '1'
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 2Gi
                periodSeconds: 10
                failureThreshold: 25
                successThreshold: 1
          serviceAccountName: runas-anyuid
          serviceAccount: runas-anyuid
          securityContext:
            runAsUser: 0
  - apiVersion: v1
    kind: Service
    metadata:
      name: petclinic-ptc
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
      selector:
        app.kubernetes.io/instance: petclinic-ptc-main
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: petclinic-ptc
    spec:
      host: petclinic-prj-elcavn-training-ptc.apps.okd.svc.elca.ch
      path: /petclinic/
      to:
        kind: Service
        name: petclinic-ptc
      port:
        targetPort: 8080-tcp
parameters:
  - name: CONTAINER_ID
